name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
  run_if:
    if:  startsWith(github.head_ref, 'master/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Are you sure this pull request is for master branch?"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}